"""add game_sessions table

Revision ID: 33b3aa7bc4ca
Revises: f486ba1d39f3
Create Date: 2026-05-02 17:03:19.148308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b3aa7bc4ca'
down_revision: Union[str, None] = 'f486ba1d39f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
